### ISSUE TITLE
2-Condicionales

### ISSUE THREAD

**Issue by yuuues** [ProtocolNebula/Iniciacion-a-la-Programacion#8]
Condicionales tipo Coalesce

php ??
sql coalesce, ifnull, 

Seguro que hay mas cosas en otros lenguajes

**Comment by ProtocolNebula** [comment]
No es algo que suela verse (salvo algunas excepciones como || o ??), pero podría ser interesante para añadirlo en la explicación "avanzada", no recuerdo si estaba explicado algo similar en la parte de condicionales.

La parte de SQL no sé si llegaría a entrar en este temario, aunque puede ser interesante como extra.

**Comment by yuuues** [comment]
Bueno, yo me refería a ejemplos funcionales de esto, se que te orientas específicamente a javascript (dado que es de los mas sencillos de entender). En Javascript también está el "coalescing operator"

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

**Comment by ProtocolNebula** [comment]
Si, tienes razón, y de hecho me sonaba haberlo explicado... igual lo salté porque era muy específico, lo apunto para añadir.
